# Generated by Django 4.2.5 on 2023-10-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('third_name', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('post', models.IntegerField()),
                ('b_day', models.DateField()),
                ('personal_num', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=10)),
                ('family_status', models.CharField(max_length=10)),
                ('place_of_bd', models.CharField(max_length=20)),
                ('appointment_order_num', models.CharField(max_length=10)),
                ('appointment_order_date', models.DateField()),
            ],
        ),
    ]
