# Generated by Django 4.2.5 on 2023-10-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing_sizes',
            fields=[
                ('head_size', models.CharField(max_length=10)),
                ('shoes_size', models.CharField(max_length=10)),
                ('cloth_size', models.CharField(max_length=10)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Driver_license',
            fields=[
                ('A', models.BooleanField()),
                ('B', models.BooleanField()),
                ('BE', models.BooleanField()),
                ('C', models.BooleanField()),
                ('CE', models.BooleanField()),
                ('D', models.BooleanField()),
                ('DE', models.BooleanField()),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('weapon_num', models.CharField(max_length=20)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_code', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('duratin', models.CharField(max_length=10)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Relatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('third_name', models.CharField(max_length=20)),
                ('relation_degree', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('inv_num', models.CharField(max_length=20)),
                ('date_of_rec', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(max_length=20)),
                ('rights', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=10)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.rank')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=20)),
                ('date_of_graduate', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('gos_num', models.CharField(max_length=10)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.post'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.rank'),
        ),
    ]
