# Generated by Django 4.1.7 on 2023-10-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clothing_sizes_driver_license_rank_weapons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='group',
            new_name='group_num',
        ),
        migrations.AddField(
            model_name='promotions',
            name='order_num',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
