# Generated by Django 4.1.7 on 2023-10-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_group_employee_group_num_promotions_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatives',
            name='phone_number',
            field=models.CharField(default='-', max_length=12),
        ),
    ]
