# Generated by Django 4.1.7 on 2023-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_education_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
