# Generated by Django 4.1.7 on 2023-10-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_weapons_description_weapons_rec_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='status',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
    ]
