# Generated by Django 4.1.7 on 2023-10-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_weapons_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapons',
            name='rec_date',
            field=models.DateField(default=None),
        ),
    ]
