# Generated by Django 4.1.7 on 2023-10-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_weapons_rec_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapons',
            name='rec_date',
            field=models.DateField(),
        ),
    ]
