# Generated by Django 4.1.7 on 2023-10-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_weapons_rec_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='description',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
