# Generated by Django 4.2.5 on 2023-10-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_promotions_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotions',
            old_name='date',
            new_name='date_of_rec',
        ),
        migrations.RenameField(
            model_name='weapons',
            old_name='rec_date',
            new_name='date_of_rec',
        ),
        migrations.AlterField(
            model_name='employee',
            name='family_status',
            field=models.CharField(choices=[('Холост', 'Холост'), ('Женат', 'Женат'), ('В разводе', 'В разводе')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='group_num',
            field=models.CharField(choices=[('-', '-'), ('Группа 1', 'Группа 1'), ('Группа 2', 'Группа 2'), ('Группа 3', 'Группа 3'), ('Группа 4', 'Группа 4'), ('Группа 5', 'Группа 5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_num',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='inv_num',
            field=models.CharField(blank=True, default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(default='Выдано', max_length=20),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='relatives',
            name='phone_number',
            field=models.CharField(blank=True, default='-', max_length=12),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
