# Generated by Django 4.2.5 on 2023-10-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_date_promotions_date_of_rec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
