# Generated by Django 4.2.5 on 2023-10-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_driver_license_a_alter_driver_license_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='second_name',
            field=models.CharField(max_length=20),
        ),
    ]
