# Generated by Django 4.2.5 on 2023-10-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_driver_license_a_alter_driver_license_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='post_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, default='Вакант', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='third_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
