# Generated by Django 4.2.5 on 2023-10-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_employee_post_num_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='post_num',
            field=models.IntegerField(unique=True),
        ),
    ]
