# Generated by Django 4.2.5 on 2023-10-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_employee_post_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['post_num']},
        ),
    ]
