# Generated by Django 4.2.5 on 2023-10-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='appointment_order_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='appointment_order_num',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='b_day',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='family_status',
            field=models.CharField(blank=True, choices=[('Холост', 'Холост'), ('Женат', 'Женат'), ('В разводе', 'В разводе')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_num',
            field=models.CharField(blank=True, default='', max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='place_of_bd',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
