# Generated by Django 4.2.5 on 2023-10-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='b_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
