# Generated by Django 4.2.5 on 2023-10-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_employee_b_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='appointment_order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
