# Generated by Django 4.2.5 on 2023-10-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_employee_appointment_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_num',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
