# Generated by Django 4.1.7 on 2024-05-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_employee_personal_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='family_status',
            field=models.CharField(blank=True, choices=[('холост', 'холост'), ('женат', 'женат'), ('в разводе', 'в разводе')], max_length=10, null=True),
        ),
    ]
