# Generated by Django 4.1.7 on 2024-05-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_employee_family_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_license',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='Clothing_sizes',
        ),
        migrations.DeleteModel(
            name='Driver_license',
        ),
    ]
